### ISSUE TITLE
Why is 'position' a double?

### ISSUE THREAD

**Issue by guillermin** [Pyozer/dots_indicator#16]
To me it makes sense that both 'dotCount' and 'position' should be int ('dotCount' is the number of dots, and 'position' is the index of the current dot). Why is 'position' a double? What does it mean for position to be 1.5?

**Comment by Pyozer** [comment]
Hi @guillermin,

`position` is a double because there is an animations (using a `lerp`), it's not 1, 2 or 3, it can be also 1, 1.2, 1.4, 1.6, ....
So a 1.5 position is when dot position is moving from 1 to 2.
GIF on the README are old, you can check GIF on [introduction_screen](https://github.com/Pyozer/introduction_screen) package to see what 1.5 position is.

**Comment by erf** [comment]
@Pyozer but should you not separate between the API for setting a page and the animation value? I don't think users will set fractional numbers or use the API to animate between pages, that happens "under-the-hood"

**Comment by Pyozer** [comment]
@erf I understand what you mean, but there is no real "animation" inside the dots_indicator package. It's not like if you provide 1 and change it to 2, it will create an animation, no, it will just use a `lerp` from the position value. This is very useful when you use it with a PageView for example. It allows you to synchronize the position of the PageView (which is also a duplicate) and the position of the dots. So it won't be directly from position 1 to position 2, but if you want to do position 1 to 2 directly you can. Having a double allows many more possibilities than a single Int.

**Comment by erf** [comment]
@Pyozer but do you think the user will pass a double? why can't the API take a int and then you just convert it to a double in the constructor? And why do you return a double onTap, parsed from a int, and not just the int of which dot was pressed?

**Comment by Pyozer** [comment]
@erf When you say "user", do you mean the user who uses your application or the developer?
It is obvious that the user won't pass a double and won't pass an int either, he doesn't have to manage that. For the developer, in the general case you will not directly pass a value (int or double), in many cases it is from a controller/callback (e.g. PageView, which is usually a double).

If you pass an int, it won't be possible to have "transitions" or if it's the package that handles the double, it will be an unsynchronized transition (not all transitions/animations are linear, you can use different curves, so you can't guarantee that the dots will be synchronized with the PageView for example).

For the onTap, I agree with you more, an int could be returned because you can't tap between two 2 points, it's only on the first, second, ... dot. But to keep consistency it's a double.

In which case do you use or plan to use this package ?
Have you seen the example GIFs on the introduction_screen package? If so, how would you do to synchronize the page changes of a PageView while passing an Int?

**Comment by erf** [comment]
@Pyozer when i say "user" i mean "developer" or user of the package. I use `dots_indicator` now in my app in addition to PageView, but i keep a `int currentPageIndex` to keep track of which page i'm on, which is passed to`DotsIndicator` and which i update `onTap`, and the widgets are again updated by setState (with the new value).

**Comment by erf** [comment]
@Pyozer when i say "user" i mean "developer" or user of the package. I use `dots_indicator` now in my app in addition to PageView, but i keep a `int currentPageIndex` to keep track of which page i'm on, which is passed to`DotsIndicator` and which i update `onTap`, and the widgets are again updated by setState (with the new value). onTap is calling  pageController.animateToPage which takes a int page. Maybe i'm doing something wrong here, but i need an int to check which page i'm on. It makes sense to me to pass an index [0, dotsCount] which is then used to create a new private double for animation / position. Also returning an int onDot makes sense to me.

**Comment by Pyozer** [comment]
@erf I checked what the callback type of PageView `onChange` was, I was wrong, it's an Int. But this callback is called only after the animation is finished and the page has finished changing. So if you want to move the dots only after the page change, it's ok and it will work (in this case the position of the dots indicator can be an Int), but for me it's not good and sexy. I think the goal of a package is to be used by as many people as possible, so you have to think about all possibilities.

By setting an Int for positions, you close off a lot of functionality. With a double, you allow those who want to use an int (double.toInt()), but also those who want to use a double to have a "progression" / "animation" of the dots like in the introduction_screen package. In this package I wrapped `PageView` with a `NotificationListener<ScrollNotification>`, it provides an `onNotification` callback on scroll changes (1, 1.1, 1.2, ... 2, 2.1, 2.2, ...) and not just on a page change (1 to 2, 2 to 3, etc...), so page is a double. Like you, I have a state with currentPage but with `double` type.
Doing this, allow to have something like this:
https://github.com/Pyozer/introduction_screen/blob/master/demo/example.gif

To be honest, I'm not going to change the double to an int, sorry :/ But I totally understand why you ask that.

**Comment by erf** [comment]
@Pyozer ah, i think i understand now.. i'm lacking that smooth animation. I tried out your package before, but i decided to make my own, maybe i should give your's another try or look into solving mye problem differently. Thank you for your patience.

**Comment by Pyozer** [comment]
No problem, I close this issue, if you have any other question do not hesitate ;)

**Comment by erf** [comment]
Ok:) Btw i think OnBoardingPage in your example could be a StatelessLess Widget?

**Comment by jeanlucthumm** [comment]
Given 3.0 changed the double to an int, how can we control in between states now?

**Comment by Pyozer** [comment]
@jeanlucthumm I'm also replying here just in case, but 3.0.0 was a mistake and should never have been made.
Use 2.1.2 until I fix this.
